name: Hello World
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      
  second_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 2"
